**BUSINESS SALES PERFORMANCE**

In [38]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error as mse

In [16]:
#reading data
df=pd.read_csv("https://www.dropbox.com/s/argivhofekhaoau/BusinessSales.csv?dl=1")

In [17]:
df.head()

division  level of education  training level  work experience  \
0        peripherals  associate's degree               1                2   
1    office supplies         high school               0                4   
2           printers  associate's degree               0                6   
3  computer software  associate's degree               2                5   
4  computer hardware        some college               1                2   

   salary   sales  
0   66790  193711  
1   63143  200167  
2   86480  274258  
3  103573  358491  
4   72166  216003

In [18]:
df.describe

<bound method NDFrame.describe of               division  level of education  training level  work experience  \
0          peripherals  associate's degree               1                2   
1      office supplies         high school               0                4   
2             printers  associate's degree               0                6   
3    computer software  associate's degree               2                5   
4    computer hardware        some college               1                2   
..                 ...                 ...             ...              ...   
995  computer software  associate's degree               0                3   
996        peripherals  associate's degree               2                7   
997  computer hardware  associate's degree               0                6   
998    office supplies  associate's degree               0               11   
999           printers        some college               1                4   

     salary   sal

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   division            1000 non-null   object
 1   level of education  1000 non-null   object
 2   training level      1000 non-null   int64 
 3   work experience     1000 non-null   int64 
 4   salary              1000 non-null   int64 
 5   sales               1000 non-null   int64 
dtypes: int64(4), object(2)
memory usage: 47.0+ KB


In [ ]:
df = df.fillna(df.mean())


In [21]:
df = pd.get_dummies(df)

In [22]:
df

training level  work experience  salary   sales  \
0                 1                2   66790  193711   
1                 0                4   63143  200167   
2                 0                6   86480  274258   
3                 2                5  103573  358491   
4                 1                2   72166  216003   
..              ...              ...     ...     ...   
995               0                3   80539  179264   
996               2                7   91699  353306   
997               0                6   92167  229316   
998               0               11   98525  385250   
999               1                4   74691  265768   

     division_computer hardware  division_computer software  \
0                             0                           0   
1                             0                           0   
2                             0                           0   
3                             0                           1   
4                             1                           0   
..                          ...                         ...   
995                           0                           1   
996                           0                           0   
997                           1                           0   
998                           0                           0   
999                           0                           0   

     division_office supplies  division_peripherals  division_printers  \
0                           0                     1                  0   
1                           1                     0                  0   
2                           0                     0                  1   
3                           0                     0                  0   
4                           0                     0                  0   
..                        ...                   ...                ...   
995                         0                     0                  0   
996                         0                     1                  0   
997                         0                     0                  0   
998                         1                     0                  0   
999                         0                     0                  1   

     level of education_associate's degree  \
0                                        1   
1                                        0   
2                                        1   
3                                        1   
4                                        0   
..                                     ...   
995                                      1   
996                                      1   
997                                      1   
998                                      1   
999                                      0   

     level of education_bachelor's degree  level of education_high school  \
0                                       0                               0   
1                                       0                               1   
2                                       0                               0   
3                                       0                               0   
4                                       0                               0   
..                                    ...                             ...   
995                                     0                               0   
996                                     0                               0   
997                                     0                               0   
998                                     0                               0   
999                                     0                               0   

     level of education_master's degree  level of education_some college  
0                                     0                                0  
1                                     0                   

In [23]:
df.columns

Index(['training level', 'work experience', 'salary', 'sales',
       'division_computer hardware', 'division_computer software',
       'division_office supplies', 'division_peripherals', 'division_printers',
       'level of education_associate's degree',
       'level of education_bachelor's degree',
       'level of education_high school', 'level of education_master's degree',
       'level of education_some college'],
      dtype='object')

In [25]:
df=df[['training level', 'work experience', 'salary',
       'division_computer hardware', 'division_computer software',
       'division_office supplies', 'division_peripherals', 'division_printers',
       'level of education_associate\'s degree',
       'level of education_bachelor\'s degree',
       'level of education_high school', 'level of education_master\'s degree',
       'level of education_some college','sales']]

In [26]:
df.head()

training level  work experience  salary  division_computer hardware  \
0               1                2   66790                           0   
1               0                4   63143                           0   
2               0                6   86480                           0   
3               2                5  103573                           0   
4               1                2   72166                           1   

   division_computer software  division_office supplies  division_peripherals  \
0                           0                         0                     1   
1                           0                         1                     0   
2                           0                         0                     0   
3                           1                         0                     0   
4                           0                         0                     0   

   division_printers  level of education_associate's degree  \
0                  0                                      1   
1                  0                                      0   
2                  1                                      1   
3                  0                                      1   
4                  0                                      0   

   level of education_bachelor's degree  level of education_high school  \
0                                     0                               0   
1                                     0                               1   
2                                     0                               0   
3                                     0                               0   
4                                     0                               0   

   level of education_master's degree  level of education_some college   sales  
0                                   0                                0  193711  
1                                   0                                0  200167  
2                                   0                                0  274258  
3                                   0                                0  358491  
4                                   0                                1  216003

In [27]:
df.corr()

training level  work experience  \
training level                               1.000000         0.019866   
work experience                              0.019866         1.000000   
salary                                       0.325558         0.855077   
division_computer hardware                   0.024743         0.016846   
division_computer software                  -0.047854        -0.001671   
division_office supplies                    -0.011977         0.072852   
division_peripherals                         0.010566        -0.053674   
division_printers                            0.010548        -0.033718   
level of education_associate's degree        0.037811        -0.013799   
level of education_bachelor's degree        -0.034122         0.102521   
level of education_high school               0.005322        -0.018149   
level of education_master's degree           0.034792        -0.034357   
level of education_some college             -0.025363        -0.033738   
sales                                        0.523738         0.819134   

                                         salary  division_computer hardware  \
training level                         0.325558                    0.024743   
work experience                        0.855077                    0.016846   
salary                                 1.000000                    0.083558   
division_computer hardware             0.083558                    1.000000   
division_computer software             0.190194                   -0.130131   
division_office supplies              -0.019635                   -0.262938   
division_peripherals                  -0.058654                   -0.258860   
division_printers                     -0.113089                   -0.247308   
level of education_associate's degree  0.102284                    0.005869   
level of education_bachelor's degree   0.185639                   -0.019372   
level of education_high school        -0.127822                   -0.021542   
level of education_master's degree     0.010299                    0.014927   
level of education_some college       -0.143459                    0.016998   
sales                                  0.904241                    0.027973   

                                       division_computer software  \
training level                                          -0.047854   
work experience                                         -0.001671   
salary                                                   0.190194   
division_computer hardware                              -0.130131   
division_computer software                               1.000000   
division_office supplies                                -0.175701   
division_peripherals                                    -0.172976   
division_printers                                       -0.165256   
level of education_associate's degree                   -0.002383   
level of education_bachelor's degree                     0.013329   
level of education_high school                           0.031325   
level of education_master's degree                      -0.018688   
level of education_some college                         -0.022244   
sales                                                   -0.021031   

                                       division_office supplies  \
training level                                        -0.011977   
work experience                                        0.072852   
salary                                                -0.019635   
division_computer hardware                            -0.262938   
division_computer software                            -0.175701   
division_office supplies                               1.000000   
division_peripherals                                  -0.349507   
division_printers                                     -0.333910   
level of education_associate's degree                 -0.043183   
level of education_bachelor's degree

In [28]:
x=df.iloc[:,0:-1].values
y=df.iloc[:,-1:].values

In [29]:
print(x)
print(y)

[[    1     2 66790 ...     0     0     0]
 [    0     4 63143 ...     1     0     0]
 [    0     6 86480 ...     0     0     0]
 ...
 [    0     6 92167 ...     0     0     0]
 [    0    11 98525 ...     0     0     0]
 [    1     4 74691 ...     0     0     1]]
[[193711]
 [200167]
 [274258]
 [358491]
 [216003]
 [242302]
 [156463]
 [498416]
 [374123]
 [403107]
 [284888]
 [429724]
 [217667]
 [325579]
 [162686]
 [463622]
 [401124]
 [249027]
 [438155]
 [390213]
 [318580]
 [240800]
 [386894]
 [502718]
 [305180]
 [493381]
 [304338]
 [477475]
 [295335]
 [394190]
 [314188]
 [443979]
 [450840]
 [512242]
 [445485]
 [410081]
 [245077]
 [413202]
 [392461]
 [536784]
 [346714]
 [268547]
 [223996]
 [256885]
 [420377]
 [221787]
 [232184]
 [231027]
 [224782]
 [272695]
 [316405]
 [334659]
 [348817]
 [336992]
 [212626]
 [430676]
 [311083]
 [305494]
 [223698]
 [609671]
 [154767]
 [440473]
 [405426]
 [351692]
 [335783]
 [373602]
 [156432]
 [341674]
 [277456]
 [335176]
 [374324]
 [386594]
 [492301]
 [4370

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [31]:
print(x_train)
print(y_train)

[[     1      5  86121 ...      0      0      1]
 [     1      3  76774 ...      0      0      0]
 [     3      6 105926 ...      0      0      0]
 ...
 [     2      3  83483 ...      0      0      1]
 [     0      8  88502 ...      0      0      1]
 [     0      2  71430 ...      0      0      0]]
[[332592]
 [243161]
 [473612]
 [431067]
 [253871]
 [295853]
 [526254]
 [521983]
 [203314]
 [298302]
 [378440]
 [296549]
 [339333]
 [318638]
 [347924]
 [346654]
 [328728]
 [331681]
 [116069]
 [341343]
 [421860]
 [372397]
 [434285]
 [441284]
 [396107]
 [195505]
 [391533]
 [436219]
 [316405]
 [319376]
 [281373]
 [412083]
 [440473]
 [192601]
 [400198]
 [379420]
 [221787]
 [120504]
 [326614]
 [338289]
 [207167]
 [121385]
 [314188]
 [437491]
 [294141]
 [331769]
 [230665]
 [316322]
 [404506]
 [482178]
 [224471]
 [392647]
 [368984]
 [371867]
 [326213]
 [134928]
 [494449]
 [321399]
 [289823]
 [329857]
 [253451]
 [240000]
 [390213]
 [265808]
 [305525]
 [311831]
 [129600]
 [322514]
 [374280]
 [261059]


In [32]:
print(len(x_train),len(x_test))

750 250


In [33]:
#linear Regression
lr_regressor=LinearRegression()
lr_regressor.fit(x_train,y_train)
y_pred_lr=lr_regressor.predict(x_test)
print(r2_score(y_test,y_pred_lr))
print(mse(y_test,y_pred_lr)**0.5)

0.9598586731561004
23705.359245981548


In [35]:
print(lr_regressor.coef_,lr_regressor.intercept_)

[[ 3.85529297e+04  1.29947340e+04  3.45926888e+00 -1.89153654e+03
  -3.57472771e+04  1.49410585e+04  7.85341969e+03  1.48443354e+04
  -2.65256513e+03 -1.61999130e+04  2.52404599e+04 -1.52305818e+04
   8.84260002e+03]] [-111908.69968309]


In [36]:
df.columns

Index(['training level', 'work experience', 'salary',
       'division_computer hardware', 'division_computer software',
       'division_office supplies', 'division_peripherals', 'division_printers',
       'level of education_associate's degree',
       'level of education_bachelor's degree',
       'level of education_high school', 'level of education_master's degree',
       'level of education_some college', 'sales'],
      dtype='object')

In [39]:
#Random Forest Regression
rf_regressor=RandomForestRegressor()
rf_regressor.fit(x_train,y_train)
y_pred_rf=rf_regressor.predict(x_test)
print(r2_score(y_test,y_pred_rf))
print(mse(y_test,y_pred_rf)**0.5)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


0.9360996053568235
29909.038349220868
